// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBI8KnrfQgoS8D48kuxBTq5FONOd9DKgE4',
    appId: '1:766436027583:web:6d05eb486eed987cf12a0a',
    messagingSenderId: '766436027583',
    projectId: 'flutterauth-b0783',
    authDomain: 'flutterauth-b0783.firebaseapp.com',
    storageBucket: 'flutterauth-b0783.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6YDwdIYgW8OHjbEocCIWmTFXh0E9KE54',
    appId: '1:766436027583:android:033516aff4b45536f12a0a',
    messagingSenderId: '766436027583',
    projectId: 'flutterauth-b0783',
    storageBucket: 'flutterauth-b0783.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfJMPTT8QKIygZjwUvOXpeXLuEXsvoAqY',
    appId: '1:766436027583:ios:7cbdbd1cefa9e240f12a0a',
    messagingSenderId: '766436027583',
    projectId: 'flutterauth-b0783',
    storageBucket: 'flutterauth-b0783.firebasestorage.app',
    iosBundleId: 'com.example.appAiQuran',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfJMPTT8QKIygZjwUvOXpeXLuEXsvoAqY',
    appId: '1:766436027583:ios:7cbdbd1cefa9e240f12a0a',
    messagingSenderId: '766436027583',
    projectId: 'flutterauth-b0783',
    storageBucket: 'flutterauth-b0783.firebasestorage.app',
    iosBundleId: 'com.example.appAiQuran',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBI8KnrfQgoS8D48kuxBTq5FONOd9DKgE4',
    appId: '1:766436027583:web:00cb83d2bdaab313f12a0a',
    messagingSenderId: '766436027583',
    projectId: 'flutterauth-b0783',
    authDomain: 'flutterauth-b0783.firebaseapp.com',
    storageBucket: 'flutterauth-b0783.firebasestorage.app',
  );

}